runtime: python37
entrypoint: ./run.sh
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 10m

env_variables:
  PASSE_FLAGS: "-v"

handlers:
- url: /.*
  secure: always
  script: auto
  redirect_http_response_code: 302
